GET http://localhost:5197/main/assets
Cookie: AuthToken=wzwmqrDnV298VbIkSUKs++KRqs16WCONwStC9XAqg+g=



###
POST http://localhost:5197/login
Content-Type: application/json

{
    "Username": "admin",
    "Password": "password" 
}

###
POST http://localhost:5197/login
Content-Type: application/json

{
    "Username": "ahmet",
    "Password": "sifre12345" 
}

###
POST http://localhost:5197/main
Content-Type: application/json

{
    "Type": "tarla",
    "Province": "adana",
    "District": "gol",
    "Neighborhood": "bru",
    "Block": "312",
    "Parcel": "444" 
}