// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Verim.Api.Data;

#nullable disable

namespace Verim.Api.Data.Migrations
{
    [DbContext(typeof(VerimContext))]
    [Migration("20240813111528_AddAuthTokenColumn")]
    partial class AddAuthTokenColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Verim.Api.Entities.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NeighborhoodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParcelNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetID");

                    b.HasIndex("UserId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetID = 1,
                            AssetType = "tarla",
                            BlockNumber = "6",
                            DistrictName = "golbasi",
                            NeighborhoodName = "segmenler",
                            ParcelNumber = "5",
                            ProvinceName = "ankara",
                            UserId = 1
                        },
                        new
                        {
                            AssetID = 2,
                            AssetType = "bag",
                            BlockNumber = "4",
                            DistrictName = "bozoyuk",
                            NeighborhoodName = "yildirim",
                            ParcelNumber = "3",
                            ProvinceName = "bursa",
                            UserId = 2
                        },
                        new
                        {
                            AssetID = 3,
                            AssetType = "bahce",
                            BlockNumber = "1",
                            DistrictName = "cayyolu",
                            NeighborhoodName = "demiroren",
                            ParcelNumber = "2",
                            ProvinceName = "kars",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Verim.Api.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AuthToken = "",
                            Password = "password",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            AuthToken = "",
                            Password = "C#asp.netdatabase123",
                            Username = "Ahmet"
                        },
                        new
                        {
                            UserId = 3,
                            AuthToken = "",
                            Password = "ilovegaming321",
                            Username = "coolbob"
                        });
                });

            modelBuilder.Entity("Verim.Api.Entities.Asset", b =>
                {
                    b.HasOne("Verim.Api.Entities.User", "Owner")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Verim.Api.Entities.User", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
